services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 8080:8080  # enables connecting locally via psql
    environment:
      POSTGRES_DB: pethatchers
      POSTGRES_HOST_AUTH_METHOD: trust